### ISSUE TITLE
💡[Feature]:  Image & Video Select functionality add in EditorScreen.

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#198] opened 2024-07-23 17:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![WhatsApp Image 2024-07-23 at 1 05 13 PM](https://github.com/user-attachments/assets/46243b8a-f416-4edc-abb3-f9560362e2d3)

The Code is already given, You have to make the Images and Video Dynamic, so that user can select those from their own device.

In other word, You have to complete two function in **EditorScreen**

**(i) onPressAddImage()
(ii) insertVideo()**

Restrict the media type for each function.

![image](https://github.com/user-attachments/assets/e9f34f00-8ab5-49b4-a1a8-eefa4fc8cac3)

### Task Area

`./frontend/src/screen/article/EditorScreen`

### Use Case

Feature

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Asymtode712** [comment] 2024-07-25 10:00
@SB2318 Please assign me this issue, I want to work on it

**Comment by SB2318** [comment] 2024-07-31 03:43
@Asymtode712 please give an update or unassign yourself.

**Comment by rushiii3** [comment] 2024-08-07 18:14
@SB2318, you can assign me!

**Comment by rushiii3** [comment] 2024-08-09 05:28
@SB2318, you can assign this!

**Comment by SB2318** [comment] 2024-08-09 09:17
@rushiii3 let me know if you need any help.

**Comment by rushiii3** [comment] 2024-08-09 17:25
> @rushiii3 let me know if you need any help.

I completed the add image functionality, but I have been stuck with the video add process. It just cannot read the file system, and the video does not show. I will be trying different methods and let me know if you find anything related to the video add feature

**Comment by SB2318** [comment] 2024-08-09 20:33
> > @rushiii3 let me know if you need any help.
> 
> I completed the add image functionality, but I have been stuck with the video add process. It just cannot read the file system, and the video does not show. I will be trying different methods and let me know if you find anything related to the video add feature

Use `react-native-document-picker`:

Code Reference:

import DocumentPicker from 'react-native-document-picker';

```
const handleDocumentSelection = async () => {
  try {
    const response = await DocumentPicker.pick({
      presentationStyle: 'fullScreen',
      type: ['video/mp4'],
    });
    setFileResponse(response);
  } catch (err) {
    console.warn(err);
  }
};
```

But I think your issue with EditorScreen or PreviewScreen, right?
Where video was not showing?

**Comment by SB2318** [comment] 2024-08-09 20:37
> > > @rushiii3 let me know if you need any help.
> > 
> > 
> > I completed the add image functionality, but I have been stuck with the video add process. It just cannot read the file system, and the video does not show. I will be trying different methods and let me know if you find anything related to the video add feature
> 
> Use `react-native-document-picker`:
> 
> Code Reference:
> 
> import DocumentPicker from 'react-native-document-picker';
> 
> ```
> const handleDocumentSelection = async () => {
>   try {
>     const response = await DocumentPicker.pick({
>       presentationStyle: 'fullScreen',
>       type: ['video/mp4'],
>     });
>     setFileResponse(response);
>   } catch (err) {
>     console.warn(err);
>   }
> };
> ```
> 
> But I think your issue with EditorScreen or PreviewScreen, right? Where video was not showing?

Will connect tomorrow morning, complete back button task first.

**Comment by rushiii3** [comment] 2024-08-10 06:09
> > > @rushiii3 let me know if you need any help.
> > 
> > 
> > I completed the add image functionality, but I have been stuck with the video add process. It just cannot read the file system, and the video does not show. I will be trying different methods and let me know if you find anything related to the video add feature
> 
> Use `react-native-document-picker`:
> 
> Code Reference:
> 
> import DocumentPicker from 'react-native-document-picker';
> 
> ```
> const handleDocumentSelection = async () => {
>   try {
>     const response = await DocumentPicker.pick({
>       presentationStyle: 'fullScreen',
>       type: ['video/mp4'],
>     });
>     setFileResponse(response);
>   } catch (err) {
>     console.warn(err);
>   }
> };
> ```
> 
> But I think your issue with EditorScreen or PreviewScreen, right? Where video was not showing?

The problem is in the Editor screen. When a video is inserted, it does not play in the editor screen because it does not get the path data in the html video tag, but it plays when using the react-native-video component

**Comment by SB2318** [comment] 2024-08-10 06:11
k, then has the issue resolved from your side?

**Comment by rushiii3** [comment] 2024-08-10 06:37
Check discord!

**Comment by rushiii3** [comment] 2024-08-10 07:39
@SB2318, please review PR #513

**Closed** 2024-08-10 08:34 UTC
Labels: enhancement, gssoc, level2
