### ISSUE TITLE
BUG: PR template not visible as expected

### ISSUE THREAD

**Issue by suhanipaliwal** [SB2318/UltimateHealth#49] opened 2024-05-17 21:01 UTC
I would like to add a pull request template for this repository. I believe that having a standardized template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review and merge pull requests.

Could you please assign this issue to me under GSSOC'24.

**Comment by SB2318** [comment] 2024-05-18 14:51
Hello,
@suhanipaliwal  as the issue is similar to issue no #38 .
Let me know what changes you want to make further, or You able to see the PR template with your PRs or not.

If you find any bugs, then we can consider this issue.

**Comment by suhanipaliwal** [comment] 2024-05-19 14:55
When raising a new PR, the template is not visible to edit as expected. Also, the template is in the folder of ISSUES TEMPLATE. I would like to change this.

**Comment by SB2318** [comment] 2024-05-19 15:04
> When raising a new PR, the template is not visible to edit as expected. Also, the template is in the folder of ISSUES TEMPLATE. I would like to change this.

Good Observation! Okay I am assigning this issue to you.

**Closed** 2024-05-22 14:30 UTC
Labels: good first issue, gssoc, level1
