### ISSUE TITLE
💡[FEATURE]: Design Signup Module

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#61] opened 2024-05-20 03:53 UTC
![image](https://github.com/SB2318/UltimateHealth/assets/87614560/f8afabd0-36ce-438d-96ef-2ef119a68eee)

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/3648b893-4706-44ad-a491-668f7f28771b)

### Instructions:

* Use **react-native-vector-icons** as much as possible.
* Give Password **show-hide** feature.
* For **Doctor's Specialization**  part as of now create a static list with 5 types, and attach the list with **dropdown.**
     example :[ "Cardiology", "Dermatology", "Pediatrics"]
* Differ the text and numbers edit-text field.

**Figma file** will provided in person, if needed.

**Comment by MaryamMohamedYahya** [comment] 2024-05-20 17:30
Please assign this to me as soon as the prototype is ready

**Comment by rushiii3** [comment] 2024-05-20 17:33
hey @SB2318, i would like to do this task.

**Comment by ParthNakum21** [comment] 2024-05-22 14:50
Hello @SB2318, I'm interested in contributing to the project by designing Sign Up page. Could you please assign this task to me under GSSoC with appropriate level?

**Comment by SB2318** [comment] 2024-05-23 07:25
@MaryamMohamedYahya  are you ready to take this task?

**Comment by MaryamMohamedYahya** [comment] 2024-05-23 11:20
> @MaryamMohamedYahya are you ready to take this task?

Yes

**Comment by SB2318** [comment] 2024-05-28 19:32
@MaryamMohamedYahya  any update?

**Comment by SB2318** [comment] 2024-05-29 10:17
@ParthNakum21  would you like to work on this task?

**Comment by ParthNakum21** [comment] 2024-05-29 11:00
> @ParthNakum21 would you like to work on this task?

Yes, I am ready to work on this issue.

**Comment by SB2318** [comment] 2024-05-29 11:21
@ParthNakum21 please reach out if you face any difficulty with the issue.

**Comment by ParthNakum21** [comment] 2024-05-29 13:51
> @ParthNakum21 please reach out if you face any difficulty with the issue.

Thank you, Working on it!

**Comment by SB2318** [comment] 2024-05-31 04:25
@ParthNakum21 update me.

**Comment by ParthNakum21** [comment] 2024-05-31 07:35
Hello @SB2318, I am encountering some issues with starting the project. I have gone through the Readme file and also some articles to solve this, but I failed. Would you be able to assist me with this?

**Comment by SB2318** [comment] 2024-05-31 07:42
> Hello @SB2318, I am encountering some issues with starting the project. I have gone through the Readme file and also some articles to solve this, but I failed. Would you be able to assist me with this?

okay, please share your discord_id

**Comment by ParthNakum21** [comment] 2024-05-31 09:06
> > Hello @SB2318, I am encountering some issues with starting the project. I have gone through the Readme file and also some articles to solve this, but I failed. Would you be able to assist me with this?
> 
> okay, please share your discord_id

Discord ID: parthnakum21

**Closed** 2024-06-07 17:39 UTC
Labels: enhancement, good first issue, gssoc, design, level3, mobile-task, in-progress
