### ISSUE TITLE
💡[FEATURE]:  Add a show-hide feature for the password field in a login page

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#77] opened 2024-05-23 07:47 UTC
**Add an eye icon at the right corner and give a show-hide feature.**

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/965efd63-21f6-42f2-a4e8-d7833d945cbe)

**Work Area:** LoginScreen

**Work Type:**  Design

### Steps:

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/3156056e-2009-4e15-8f9f-eb1b5de8ce33)

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/1383f482-c989-447a-9302-a249374c0045)

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/bf1fbe67-0eed-4281-8555-9db5ea30f542)

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/3350f34e-b43b-4dfa-931f-958ee58ba4bd)

@512ishani  Please check the flow and clone **develop** branch, Please follow Contributing.md file.

**Comment by diksha2774** [comment] 2024-05-23 09:51
I'm excited to contribute to the GSSoC 2024 project and would love to be assigned issue @SB2318.

**Comment by ayushkamboj18** [comment] 2024-05-23 09:53
Hey @SB2318  I can start working this issue. Would you assign this to me

**Comment by rushiii3** [comment] 2024-05-23 10:26
hey @SB2318, i would like to do this issue assign me

**Comment by anurag-adk** [comment] 2024-05-28 17:23
Hi there......It's been 5 days and the issue is yet to be solved. I would love to work on it so can you assign me this issue? Thanks!

**Comment by SB2318** [comment] 2024-05-28 17:50
@diksha2774  any update?

**Comment by SB2318** [comment] 2024-05-29 10:18
@ayushkamboj18  would you like to take this task?

**Comment by ayushkamboj18** [comment] 2024-05-29 10:21
@SB2318 yes, i can do it

**Comment by ayushkamboj18** [comment] 2024-05-29 10:47
I unassigned myself because I think this project involves React, and I do not know about app development.

**Comment by SB2318** [comment] 2024-05-29 10:49
@anurag-adk  do you want to take this task?

**Comment by anurag-adk** [comment] 2024-05-29 11:24
@SB2318 Sure!

**Comment by akshathere** [comment] 2024-05-29 14:37
hey @SB2318 if no one is doing this task right now 
Can you assign this task to me?

**Comment by 512ishani** [comment] 2024-05-31 07:19
@SB2318 i would really love to work on this issue could you assign it to me ?

**Comment by akshathere** [comment] 2024-06-01 13:17
@SB2318  its been 2 days since anurag-adk has removed their assignment 
Can you please assign this issue again since no one is assigned right now

**Comment by nishant0708** [comment] 2024-06-01 19:12
hey @SB2318  can i work on this issue?

**Comment by SB2318** [comment] 2024-06-05 14:13
@512ishani This issue seems to be a little bit tough, I also found some design bugs that arise due to the changes, let me know If you are facing any difficulties, Or if it seems to be very tough for you, then you can unassign yourself.

**Comment by 512ishani** [comment] 2024-06-08 08:02
@SB2318 I found this issue a little bit tough , i tried but could not solve it . So i have unassigned myself

**Comment by SB2318** [comment] 2024-06-08 08:23
@nishant0708  will you want to take this issue?

**Comment by nishant0708** [comment] 2024-06-08 09:01
Yess

**Closed** 2024-06-12 12:24 UTC
Labels: good first issue, gssoc, level1, auth
